In [183]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [184]:
df=pd.read_csv('customer_support_tickets.csv')

In [185]:
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [186]:
uselesscols=['Customer Name','Customer Email','Customer Age','Customer Gender']
df=df.drop(columns=uselesscols)

In [187]:
df

,Ticket ID,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8464,8465,LG OLED,2021-12-08,Product inquiry,Installation support,My {product_purchased} is making strange noise...,Open,NaN,Low,Phone,NaN,NaN,NaN
8465,8466,Bose SoundLink Speaker,2020-02-22,Technical issue,Refund request,I'm having an issue with the {product_purchase...,Open,NaN,Critical,Email,NaN,NaN,NaN
8466,8467,GoPro Action Camera,2021-08-17,Technical issue,Account access,I'm having an issue with the {product_purchase...,Closed,Eight account century nature kitchen.,High,Social media,2023-06-01 09:44:22,2023-06-01 04:31:22,3.0
8467,8468,PlayStation,2021-10-16,Product inquiry,Payment issue,I'm having an issue with the {product_purchase...,Closed,We seat culture plan.,Medium,Email,2023-06-01 18:28:24,2023-06-01 05:32:24,3.0
8468,8469,Philips Hue Lights,2020-06-01,Billing inquiry,Hardware issue,There seems to be a hardware problem with my {...,Open,NaN,High,Phone,NaN,NaN,NaN

In [188]:
df.columns

Index(['Ticket ID', 'Product Purchased', 'Date of Purchase', 'Ticket Type',
       'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution',
       'Ticket Priority', 'Ticket Channel', 'First Response Time',
       'Time to Resolution', 'Customer Satisfaction Rating'],
      dtype='str')

In [189]:
df['Product Purchased']=df['Product Purchased'].fillna('device')
df['Ticket Description']=df['Ticket Description'].fillna('')
def merge_p_t(row):
    desc=row['Ticket Description']
    prod=str(row['Product Purchased'])
    desc=desc.replace('{product_purchased}',prod)
    return desc
df['Ticket Description']=df.apply(merge_p_t,axis=1)

In [190]:
df

,Ticket ID,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the GoPro Hero. Pleas...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the LG Smart TV. Plea...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my Dell XPS. The Del...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the Microsoft Office....,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the Autodesk AutoCAD....,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8464,8465,LG OLED,2021-12-08,Product inquiry,Installation support,My LG OLED is making strange noises and not fu...,Open,NaN,Low,Phone,NaN,NaN,NaN
8465,8466,Bose SoundLink Speaker,2020-02-22,Technical issue,Refund request,I'm having an issue with the Bose SoundLink Sp...,Open,NaN,Critical,Email,NaN,NaN,NaN
8466,8467,GoPro Action Camera,2021-08-17,Technical issue,Account access,I'm having an issue with the GoPro Action Came...,Closed,Eight account century nature kitchen.,High,Social media,2023-06-01 09:44:22,2023-06-01 04:31:22,3.0
8467,8468,PlayStation,2021-10-16,Product inquiry,Payment issue,I'm having an issue with the PlayStation. Plea...,Closed,We seat culture plan.,Medium,Email,2023-06-01 18:28:24,2023-06-01 05:32:24,3.0
8468,8469,Philips Hue Lights,2020-06-01,Billing inquiry,Hardware issue,There seems to be a hardware problem with my P...,Open,NaN,High,Phone,NaN,NaN,NaN

In [191]:
df=df.drop('Product Purchased',axis=1)

In [192]:
df

,Ticket ID,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,2021-03-22,Technical issue,Product setup,I'm having an issue with the GoPro Hero. Pleas...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the LG Smart TV. Plea...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,2020-07-14,Technical issue,Network problem,I'm facing a problem with my Dell XPS. The Del...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,2020-11-13,Billing inquiry,Account access,I'm having an issue with the Microsoft Office....,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the Autodesk AutoCAD....,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8464,8465,2021-12-08,Product inquiry,Installation support,My LG OLED is making strange noises and not fu...,Open,NaN,Low,Phone,NaN,NaN,NaN
8465,8466,2020-02-22,Technical issue,Refund request,I'm having an issue with the Bose SoundLink Sp...,Open,NaN,Critical,Email,NaN,NaN,NaN
8466,8467,2021-08-17,Technical issue,Account access,I'm having an issue with the GoPro Action Came...,Closed,Eight account century nature kitchen.,High,Social media,2023-06-01 09:44:22,2023-06-01 04:31:22,3.0
8467,8468,2021-10-16,Product inquiry,Payment issue,I'm having an issue with the PlayStation. Plea...,Closed,We seat culture plan.,Medium,Email,2023-06-01 18:28:24,2023-06-01 05:32:24,3.0
8468,8469,2020-06-01,Billing inquiry,Hardware issue,There seems to be a hardware problem with my P...,Open,NaN,High,Phone,NaN,NaN,NaN

In [193]:
df.head()

,Ticket ID,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,2021-03-22,Technical issue,Product setup,I'm having an issue with the GoPro Hero. Pleas...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the LG Smart TV. Plea...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,2020-07-14,Technical issue,Network problem,I'm facing a problem with my Dell XPS. The Del...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,2020-11-13,Billing inquiry,Account access,I'm having an issue with the Microsoft Office....,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the Autodesk AutoCAD....,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [194]:
df=df.drop('Resolution',axis=1)

In [195]:
df.head()

,Ticket ID,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,2021-03-22,Technical issue,Product setup,I'm having an issue with the GoPro Hero. Pleas...,Pending Customer Response,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the LG Smart TV. Plea...,Pending Customer Response,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,2020-07-14,Technical issue,Network problem,I'm facing a problem with my Dell XPS. The Del...,Closed,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,2020-11-13,Billing inquiry,Account access,I'm having an issue with the Microsoft Office....,Closed,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the Autodesk AutoCAD....,Closed,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [196]:
df['Customer Satisfaction Rating'].isnull().sum()

np.int64(5700)

In [197]:
df=df.drop(columns=['First Response Time','Time to Resolution','Customer Satisfaction Rating','Date of Purchase','Ticket Status','Ticket Channel','Ticket ID'])

In [198]:
df

,Ticket Type,Ticket Subject,Ticket Description,Ticket Priority
0,Technical issue,Product setup,I'm having an issue with the GoPro Hero. Pleas...,Critical
1,Technical issue,Peripheral compatibility,I'm having an issue with the LG Smart TV. Plea...,Critical
2,Technical issue,Network problem,I'm facing a problem with my Dell XPS. The Del...,Low
3,Billing inquiry,Account access,I'm having an issue with the Microsoft Office....,Low
4,Billing inquiry,Data loss,I'm having an issue with the Autodesk AutoCAD....,Low
...,...,...,...,...
8464,Product inquiry,Installation support,My LG OLED is making strange noises and not fu...,Low
8465,Technical issue,Refund request,I'm having an issue with the Bose SoundLink Sp...,Critical
8466,Technical issue,Account access,I'm having an issue with the GoPro Action Came...,High
8467,Product inquiry,Payment issue,I'm having an issue with the PlayStation. Plea...,Medium
8468,Billing inquiry,Hardware issue,There seems to be a hardware problem with my P...,High

In [199]:
df['Ticket Type'].unique()

<ArrowStringArray>
[     'Technical issue',      'Billing inquiry', 'Cancellation request',
      'Product inquiry',       'Refund request']
Length: 5, dtype: str

In [200]:
df['Ticket Subject'].unique()

<ArrowStringArray>
[           'Product setup', 'Peripheral compatibility',
          'Network problem',           'Account access',
                'Data loss',            'Payment issue',
           'Refund request',             'Battery life',
     'Installation support',             'Software bug',
           'Hardware issue',   'Product recommendation',
         'Delivery problem',            'Display issue',
     'Cancellation request',    'Product compatibility']
Length: 16, dtype: str

In [201]:
df.columns

Index(['Ticket Type', 'Ticket Subject', 'Ticket Description',
       'Ticket Priority'],
      dtype='str')

In [202]:
df.head()

,Ticket Type,Ticket Subject,Ticket Description,Ticket Priority
0,Technical issue,Product setup,I'm having an issue with the GoPro Hero. Pleas...,Critical
1,Technical issue,Peripheral compatibility,I'm having an issue with the LG Smart TV. Plea...,Critical
2,Technical issue,Network problem,I'm facing a problem with my Dell XPS. The Del...,Low
3,Billing inquiry,Account access,I'm having an issue with the Microsoft Office....,Low
4,Billing inquiry,Data loss,I'm having an issue with the Autodesk AutoCAD....,Low

In [203]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Ticket Type         8469 non-null   str
 1   Ticket Subject      8469 non-null   str
 2   Ticket Description  8469 non-null   str
 3   Ticket Priority     8469 non-null   str
dtypes: str(4)
memory usage: 2.8 MB

In [204]:
df.isnull().sum()

Ticket Type           0
Ticket Subject        0
Ticket Description    0
Ticket Priority       0
dtype: int64

In [205]:
df['full_text']=(df['Ticket Subject'].str.strip()+":"+df['Ticket Description'].str.strip()).str.strip()

In [206]:
df=df.drop(columns=['Ticket Subject','Ticket Description'])

In [207]:
df

,Ticket Type,Ticket Priority,full_text
0,Technical issue,Critical,Product setup:I'm having an issue with the GoP...
1,Technical issue,Critical,Peripheral compatibility:I'm having an issue w...
2,Technical issue,Low,Network problem:I'm facing a problem with my D...
3,Billing inquiry,Low,Account access:I'm having an issue with the Mi...
4,Billing inquiry,Low,Data loss:I'm having an issue with the Autodes...
...,...,...,...
8464,Product inquiry,Low,Installation support:My LG OLED is making stra...
8465,Technical issue,Critical,Refund request:I'm having an issue with the Bo...
8466,Technical issue,High,Account access:I'm having an issue with the Go...
8467,Product inquiry,Medium,Payment issue:I'm having an issue with the Pla...
8468,Billing inquiry,High,Hardware issue:There seems to be a hardware pr...

In [208]:
df['Ticket Type'].unique()

<ArrowStringArray>
[     'Technical issue',      'Billing inquiry', 'Cancellation request',
      'Product inquiry',       'Refund request']
Length: 5, dtype: str

In [209]:
df['Ticket Priority'].unique()

<ArrowStringArray>
['Critical', 'Low', 'High', 'Medium']
Length: 4, dtype: str

In [210]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y_form=le.fit_transform(df['Ticket Type'])

,Ticket Type,Ticket Priority,full_text
0,Technical issue,Critical,Product setup:I'm having an issue with the GoP...
1,Technical issue,Critical,Peripheral compatibility:I'm having an issue w...
2,Technical issue,Low,Network problem:I'm facing a problem with my D...
3,Billing inquiry,Low,Account access:I'm having an issue with the Mi...
4,Billing inquiry,Low,Data loss:I'm having an issue with the Autodes...
...,...,...,...
8464,Product inquiry,Low,Installation support:My LG OLED is making stra...
8465,Technical issue,Critical,Refund request:I'm having an issue with the Bo...
8466,Technical issue,High,Account access:I'm having an issue with the Go...
8467,Product inquiry,Medium,Payment issue:I'm having an issue with the Pla...
8468,Billing inquiry,High,Hardware issue:There seems to be a hardware pr...